### ISSUE TITLE
java.lang.NoClassDefFoundError: edx/core/CommonProxy

### ISSUE THREAD

**Issue by thewhiterabbit** [calclavia/Electrodynamics#18]
Here is the crash report...

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 10/30/15 8:29 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: edx/core/CommonProxy
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:544)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: edx/core/CommonProxy
    at java.lang.Class.getDeclaredMethods0(Native Method)
    at java.lang.Class.privateGetDeclaredMethods(Class.java:2688)
    at java.lang.Class.getDeclaredMethods(Class.java:1962)
    at cpw.mods.fml.common.FMLModContainer.gatherAnnotations(FMLModContainer.java:317)
    at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:505)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:513)
    ... 10 more
Caused by: java.lang.ClassNotFoundException: edx.core.CommonProxy
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 37 more
Caused by: java.lang.NoClassDefFoundError: resonantengine/lib/mod/AbstractProxy
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 39 more
Caused by: java.lang.ClassNotFoundException: resonantengine.lib.mod.AbstractProxy
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 43 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Mac OS X (x86_64) version 10.10.1
    Java Version: 1.8.0_11, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 6129578720 bytes (5845 MB) / 6435110912 bytes (6137 MB) up to 7516192768 bytes (7168 MB)
    JVM Flags: 3 total; -Xmx7168m -XX:+UseG1GC -XX:MaxGCPauseMillis=4
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: XRay v2.11.0 MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1492 107 mods loaded, 107 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UC  mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UC  FML{7.10.99.99} [Forge Mod Loader](modpack.jar) 
    UC  Forge{10.13.4.1492} [Minecraft Forge](modpack.jar) 
    UC  appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core](minecraft.jar) 
    UC  CodeChickenCore{1.0.7.46} [CodeChicken Core](minecraft.jar) 
    UC  NotEnoughItems{1.0.5.110} [Not Enough Items](NotEnoughItems-1.7.10-1.0.5.110-universal.jar) 
    UC  OpenModsCore{0.6} [OpenModsCore](minecraft.jar) 
    UC  <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
    UC  mcdiscord{2.0.0} [MC Discord](minecraft.jar) 
    UC  bspkrsCore{6.15} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.15.jar) 
    UC  Treecapitator{1.7.10} [Treecapitator]([1.7.10]Treecapitator-universal-2.0.4.jar) 
    UC  CoFHCore{1.7.10R3.0.3} [CoFH Core](CoFHCore-[1.7.10]3.0.3-303 %281%29.jar) 
    UC  BuildCraft|Core{7.1.10} [BuildCraft](buildcraft-7.1.10.jar) 
    UC  BuildCraft|Transport{7.1.10} [BC Transport](buildcraft-7.1.10.jar) 
    UC  BuildCraft|Silicon{7.1.10} [BC Silicon](buildcraft-7.1.10.jar) 
    UC  BuildCraft|Factory{7.1.10} [BC Factory](buildcraft-7.1.10.jar) 
    UC  ComputerCraft{1.74} [ComputerCraft](ComputerCraftPlusComputerCraftEdu1.74.jar) 
    UC  IC2{2.2.999} [IndustrialCraft 2 Classic](IC2.Classic.Version.1.1.2.1.jar) 
    UC  Forestry{3.6.11.2} [Forestry for Minecraft](forestry_1.7.10-3.6.11.2.jar) 
    UC  UniversalElectricity{@MAJOR@.@MINOR@.@REVIS@} [Universal Electricity](universal-electricity-4.0.0.9-dev.jar) 
    UC  ForgeMultipart{1.2.0.344} [Forge Multipart](ForgeMultipart-1.7.10-1.2.0.344-universal.jar) 
    UC  Waila{1.5.10} [Waila](Waila-1.5.10_1.7.10.jar) 
    UC  ResonantEngine{3.0.0} [Resonant Engine](resonant-engine-3.0.0.23-core.jar) 
    UE  EDX{@MAJOR@.@MINOR@.@REVIS@} [Electrodynamics](electrodynamics-0.3.5.306-core.jar) 
    UC  ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation](ThermalFoundation-[1.7.10]1.2.0-102.jar) 
    UC  ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion](ThermalExpansion-[1.7.10]4.0.3B1-218.jar) 
    UC  LogisticsPipes{0.9.3.54} [Logistics Pipes](logisticspipes-0.9.3.54.jar) 
    UC  additionalpipes{4.7.0} [Additional Pipes](additionalpipes-4.7.0.jar) 
    UC  appliedenergistics2{rv2-stable-10} [Applied Energistics 2](appliedenergistics2-rv2-stable-10 %281%29.jar) 
    UC  asielib{0.4.2} [asielib](AsieLib-1.7.10-0.4.2.jar) 
    UC  bdlib{1.9.3.107} [BD Lib](bdlib-1.9.3.107-mc1.7.10.jar) 
    UC  BigReactors{0.4.3A} [Big Reactors](BigReactors-0.4.3A.jar) 
    UC  qmunitylib{1.0} [QmunityLib](QmunityLib-1.7.10-0.1.114-universal.jar) 
    UC  bluepower{0.2.962} [Blue Power](BluePower-1.7.10-0.2.962-universal.jar) 
    UC  BuildCraft|Builders{7.1.10} [BC Builders](buildcraft-7.1.10.jar) 
    UC  BuildCraft|Energy{7.1.10} [BC Energy](buildcraft-7.1.10.jar) 
    UC  BuildCraft|Robotics{7.1.10} [BC Robotics](buildcraft-7.1.10.jar) 
    UC  BuildCraft|Compat{7.1.1} [BuildCraft Compat](buildcraft-compat-7.1.1.jar) 
    UC  CarpentersBlocks{3.3.7} [Carpenter's Blocks](Carpenter's Blocks v3.3.7 - MC 1.7.10.jar) 
    UC  ChickenChunks{1.3.4.19} [ChickenChunks](ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
    UC  ComputerCraftEdu{1.74} [ComputerCraftEdu](ComputerCraftPlusComputerCraftEdu1.74.jar) 
    UC  MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UC  Railcraft{9.7.0.0} [Railcraft](Railcraft_1.7.10-9.7.0.0.jar) 
    UC  computronics{1.5.7} [Computronics](Computronics-1.7.10-1.5.7.jar) 
    UC  defaultkeys{1.0.24} [Default Keyconfig](defaultkeys-mc1.7.10-1.0.24.jar) 
    UC  EnderStorage{1.4.7.36} [EnderStorage](EnderStorage-1.7.10-1.4.7.36-universal.jar) 
    UC  eng_toolbox{1.2.3.0} [Engineer's Toolbox](EngineersToolbox-1.2.3.0-BETA.jar) 
    UC  McMultipart{1.2.0.344} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.2.0.344-universal.jar) 
    UC  gendustry{1.6.1.126} [GenDustry](gendustry-1.6.1.126-mc1.7.10.jar) 
    UC  IC2-Classic-Spmod{0.0.0.0} [IC2 Classic Detection Helper](IC2.Classic.Version.1.1.2.1.jar) 
    UC  IC2NuclearControl{2.3.0a-Butt} [Nuclear Control 2](IC2NuclearControl-2.3.0a-Butt.jar) 
    UC  ImmibisCore{59.1.2} [Immibis Core](immibis-core-59.1.2.jar) 
    UC  ImmibisPeripherals{59.0.2} [Immibis's Peripherals](immibis-peripherals-59.0.2.jar) 
    UC  inventorytweaks{1.59-dev-156-af3bc68} [Inventory Tweaks](InventoryTweaks-1.59-dev-156.jar) 
    UC  IronChest{6.0.60.741} [Iron Chest](Ironchest-1.7.10-6.0.60.741-universal.jar) 
    UC  itlt{0.0.8} [It's the little things](itlt-1.7.10-0.0.8.jar) 
    UC  JABBA{1.2.1} [JABBA](Jabba-1.2.1a_1.7.10.jar) 
    UC  MapWriter{2.1.8} [MapWriter](MapWriter-1.7.10-2.1.10.jar) 
    UC  MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} [MFR Compat: Applied Energistics](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UC  MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UC  MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR Compat: BackTools](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UC  MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR Compat: BuildCraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UC  MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR Compat: Chococraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UC  MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR Compat: ExtraBiomes](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UC  MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UC  MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR Compat: ForgeMicroblock](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UC  MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UC  MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR Compat: Mystcraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UC  MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UC  MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR Compat: Railcraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UC  MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR Compat: Sufficient Biomes](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UC  MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR Compat: Thaumcraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UC  MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR Compat: Thermal Expansion](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UC  MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR Compat: Tinkers' Construct](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UC  MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR Compat: TwilightForest](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UC  MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UC  MineTweaker3{3.0.10} [MineTweaker 3](MineTweaker3-1.7.10-3.0.10.jar) 
    UC  modtweaker2{0.9.2} [Mod Tweaker 2](ModTweaker2-0.9.3.jar) 
    UC  numina{0.4.0.131} [Numina](Numina-0.4.0.131.jar) 
    UC  powersuits{0.11.0.283} [MachineMuse's Modular Powersuits](ModularPowersuits-0.11.0.283.jar) 
    UC  NEIAddons{1.12.11.36} [NEI Addons](neiaddons-1.12.11.36-mc1.7.10.jar) 
    UC  NEIAddons|Developer{1.12.11.36} [NEI Addons: Developer Tools](neiaddons-1.12.11.36-mc1.7.10.jar) 
    UC  NEIAddons|AppEng{1.12.11.36} [NEI Addons: Applied Energistics 2](neiaddons-1.12.11.36-mc1.7.10.jar) 
    UC  NEIAddons|Botany{1.12.11.36} [NEI Addons: Botany](neiaddons-1.12.11.36-mc1.7.10.jar) 
    UC  NEIAddons|Forestry{1.12.11.36} [NEI Addons: Forestry](neiaddons-1.12.11.36-mc1.7.10.jar) 
    UC  NEIAddons|CraftingTables{1.12.11.36} [NEI Addons: Crafting Tables](neiaddons-1.12.11.36-mc1.7.10.jar) 
    UC  NEIAddons|ExNihilo{1.12.11.36} [NEI Addons: Ex Nihilo](neiaddons-1.12.11.36-mc1.7.10.jar) 
    UC  neiintegration{1.0.12} [NEI Integration](NEIIntegration-MC1.7.10-1.0.12.jar) 
    UC  NetherOres{1.7.10R2.3.0} [Nether Ores](NetherOres-[1.7.10]2.3.0-12.jar) 
    UC  NuclearCraft{0.0.1.5} [NuclearCraft](NuclearCraft-0.0.1.5--1.7.10.jar) 
    UC  OpenMods{0.6} [OpenMods](OpenModsLib-1.7.10-0.6.jar) 
    UC  OpenBlocks{1.3} [OpenBlocks](OpenBlocks-1.7.10-1.3.jar) 
    UC  OCS{1.7.5} [OpenCCSensors](openccsensors-1.7.5.jar) 
    UC  planetguyLib{1.9} [planetguyLib](PlanetguyLib-1.9.1.jar) 
    UC  PowerConverters3{1.7.10-2.10} [Power Converters 3](PowerConverters-1.7.10-2.10.jar) 
    UC  ProjectE{1.7.10-PE1.9.3} [ProjectE](ProjectE-1.7.10-PE1.9.3h.jar) 
    UC  quiverchevsky{b100} [QuiverBow](QuiverBow_1.7.10_b100.zip) 
    UC  RedstoneArsenal{1.7.10R1.1.1} [Redstone Arsenal](RedstoneArsenal-[1.7.10]1.1.1-89.jar) 
    UC  JAKJ_RedstoneInMotion{2.8.6} [Remain In Motion](RemainInMotion-2.8.6.jar) 
    UC  chunkbase_slimemod_ssp{2.1} [Slime Mod (SSP)](SlimeModSSP-1.7.10-2.1.jar) 
    UC  SolarFlux{1.7.10-0.8b} [Solar Flux](SolarFlux-1.7.10-0.8b.jar) 
    UC  ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics](ThermalDynamics-[1.7.10]1.1.0-161.jar) 
    UC  Tubestuff{59.0.4} [Tubestuff](tubestuff-59.0.4.jar) 
    UC  WailaHarvestability{1.1.2} [Waila Harvestability](WailaHarvestability-mc1.7.x-1.1.2.jar) 
    UC  zettaindustries{1.1} [Zetta Industries](zettaindustries-1.1-97.jar) 
    UC  aobd{2.8.4} [Another One Bites The Dust](AOBD-2.8.4.jar) 
    UC  ForgeMicroblock{1.2.0.344} [Forge Microblocks](ForgeMultipart-1.7.10-1.2.0.344-universal.jar) 
    OpenModsLib crash transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:ENABLED],[gl_capabilities_hook:FINISHED],[player_render_hook:ENABLED]
    CoFHCore: -[1.7.10]3.0.3-303
    ThermalFoundation: -[1.7.10]1.2.0-102
    ThermalExpansion: -[1.7.10]4.0.3B1-218
    AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
    MineFactoryReloaded: -[1.7.10]2.8.0-104
    NetherOres: -[1.7.10]2.3.0-12
    RedstoneArsenal: -[1.7.10]1.1.1-89
    ThermalDynamics: -[1.7.10]1.1.0-161

Looks like it's not loading the AbstractProxy class. I'm looking into it but I'm not as keen on Java as I am on PHP and javascript. If someone from the contributing team/dev team would pretty please look at this also I would be eternally happy.

When the crash happened I was running these files/versions...
electrodynamics-0.3.5.306-core.jar
NOVA-Core-Wrapper-MC1.7-0.1.0-SNAPSHOT-fat.jar
resonant-engine-3.0.0.23-core.jar
universal-electricity-4.0.0.9-dev.jar

All the other details are there in the report. Fuq, man, I really, really want this to work in 1.7.10 so bad I can taste the deuterium.

**Comment by ApplePieXpto** [comment]
look's like NOVA-Core-Wrapper-MC1.7-0.1.0-SNAPSHOT-fat.jar isn´t avaiable for download anymore, maybe calclavia forgot to pay the hosting bill on ci.novaapi.net lol
Could you provide some download link for it?

**Comment by calclavia** [comment]
https://github.com/NOVA-Team/NOVA-Core/issues/207 Contact @RX14 for the backups
