### ISSUE TITLE
How To Install?

### ISSUE THREAD

**Issue by Sermax18** [calclavia/Electrodynamics#21]

**Comment by ghost** [comment]
Install Minecraft Forge and drop the jar of EDX into the mods folder. Like any other forge mod.

**Comment by Sermax18** [comment]
where download EDX?

**Comment by ghost** [comment]
Wait... it's not that simple as I thought... there's no download button. And there is no EDX on legacy versions (I don't know if you understand me EDX = electrodynamics)

**Comment by Devalut** [comment]
So you can't use the current releases?
Dragging them into the mods folder results in nothing and even the main menu not recognizing it
